[tools]
aqua = "latest"
bottom = "latest"
cargo-binstall = "latest"
claude = "latest"
cloudflared = "latest"
cookiecutter = "latest"
direnv = "latest"
eza = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gemini-cli = "latest"
github-cli = "latest"
helix = "latest"
jq = "latest"
julia = "latest"
marp-cli = "latest"
node = "lts"
postgres = "latest"
python = "3.11.6"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
starship = "latest"
task = "latest"
terraform = "latest"
tokei = "latest"
uv = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
bat = "latest"
dust = "latest"
jjui = "latest"
jj = "latest"
firebase = "latest"
cloud-sql-proxy = "2"
xh = "latest"
delta = "latest"
hyperfine = "latest"
typst = "latest"
gcloud = "latest"
"ubi:rossmacarthur/sheldon" = "latest"
duf = "latest"

[env]
CLOUDSDK_PYTHON = "{{env.HOME}}/.local/share/mise/installs/python/3.11.6/bin/python3"
KAGGLE_CONFIG_DIR = "{{env.HOME}}/.config/kaggle"
NODE_EXTRA_CA_CERTS = "{{env.HOME}}/.config/prisma-ca.pem"
